sudo: required
services:
  - docker

before_install:
  -docker build -t bkumawat/react-test -f ./client/Dockerfile.dev ./client

script:
  - doker run bkumawat/react-test npm test -- --coverage

# Generating Production version of the docker images
after_success:
  - docker build -t bkumawat/multi-client ./client
  - docker build -t bkumawat/multi-nginx ./nginx
  - docker build -t bkumawat/multi-server ./server
  - docker build -t bkumawat/multi-worker ./worker

# Before we push our code to docker hub we need to login to docker hub
  - echo "$docker_password" | docker login - u "$docker_hub_username" --password-stdin

# Step to push this production version images to docker-hub
  - docker push bkumawat/multi-client
  - docker push bkumawat/multi-nginx
  - docker push bkumawat/multi-server
  - docker push bkumawat/multi-worker